---
# This playbook builds empty svelte page
- name: Page with database
  hosts: 127.0.0.1
  connection: local
  vars:
    app_path: "../from-scratch"

  tasks:
    - include_tasks: modules/scratch.yml
      vars:
        app_path: "../from-scratch"

    - name: Merge config files
      command: 
        chdir: "{{ app_path }}"
        cmd: git merge scratch/feature/031/config-database -m "merging config files"
    - name: Merge empty layout
      command: 
        chdir: "{{ app_path }}"
        cmd: git merge scratch/feature/060/layout-empty -m "merging empty layout"

